 /******************************************************
 * PLEASE DO NOT EDIT THIS FILE
 * the verification process may break
 * ***************************************************/

'use strict';

var fs = require('fs');
var express = require('express');
var app = express();

if (!process.env.DISABLE_XORIGIN) {
  app.use(function(req, res, next) {
    var allowedOrigins = ['https://narrow-plane.gomix.me', 'https://www.freecodecamp.com'];
    var origin = req.headers.origin || '*';
    if(!process.env.XORIG_RESTRICT || allowedOrigins.indexOf(origin) > -1){
         console.log(origin);
         res.setHeader('Access-Control-Allow-Origin', origin);
         res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
    }
    next();
  });
}

app.use('/public', express.static(process.cwd() + '/public'));

app.route('/_api/package.json')
  .get(function(req, res, next) {
    console.log('requested');
    fs.readFile(__dirname + '/package.json', function(err, data) {
      if(err) return next(err);
      res.type('txt').send(data.toString());
    });
  });
  
app.route('/')
    .get(function(req, res) {
		  res.sendFile(process.cwd() + '/views/index.html');
    })

// retrieves http headers and sends the response with the ip, language and operating system for my browser
app.route('/api')
    .get(function(req, res) {
      
      // gets the ipaddress header
      var ipHeaders = req.headers["x-forwarded-for"];
      var ipHeadersArr = ipHeaders.split(',');
      var ipAddress = ipHeadersArr[0];
      
      // gets the language header
      var languageHeaders = req.headers["accept-language"];
      var languageHeadersArr = languageHeaders.split(',');
      var language = languageHeadersArr[0];
  
      // get the OS header
      var softwareHeaders = req.headers["user-agent"];
      var softwareHeadersArrAux = softwareHeaders.split(')');
      var softwareHeadersArr = softwareHeadersArrAux[0].split('(');
      var software = softwareHeadersArr[1];
  
      res.send(JSON.stringify({ipaddress: ipAddress, language: language, software: software}));
    })


// Respond not found to all the wrong routes
app.use(function(req, res, next){
  res.status(404);
  res.type('txt').send('Not found');
});

// Error Middleware
app.use(function(err, req, res, next) {
  if(err) {
    res.status(err.status || 500)
      .type('txt')
      .send(err.message || 'SERVER ERROR');
  }  
})

app.listen(process.env.PORT, function () {
  console.log('Node.js listening ...');
});

